"""add cloudinary fields

Revision ID: 8db168b72a75
Revises: cf5c975a506d
Create Date: 2026-08-14 17:01:23.247397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db168b72a75'
down_revision: Union[str, Sequence[str], None] = 'cf5c975a506d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('cliplink', sa.Text(), nullable=False))
    op.add_column('videos', sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False))
    op.add_column('videos', sa.Column('videolink', sa.Text(), nullable=False))
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    op.drop_column('videos', 'original_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.drop_column('videos', 'videolink')
    op.drop_column('videos', 'cloudinary_public_id')
    op.drop_column('clips', 'cliplink')
    # ### end Alembic commands ###
